layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Statistics
    web_url: https://seeing-theory.brown.edu/basic-probability/index.html
    image_url: https://raw.githubusercontent.com/hafidzdaud/portal/master/assets/100px-Fisher_iris_versicolor_sepalwidth.svg.png

  - name: Optimization
    web_url: https://www.tandfonline.com/loi/gopt20
    image_url: https://raw.githubusercontent.com/hafidzdaud/portal/master/assets/1024px-Max_paraboloid.svg.png
  
  - name: Apache SPARK
    web_url: https://spark.apache.org/
    image_url: https://raw.githubusercontent.com/hafidzdaud/portal/master/assets/spark-logo-trademark.png
    
    
    
